# ============================================================
# 文明纪元整合包 - 服务器配置
# Minecraft Forge 1.20.1
# ============================================================

level-type=terralith:terralith
generator-settings={}
level-seed=
gamemode=survival
difficulty=normal
hardcore=false
allow-cheats=false
max-players=20
online-mode=true
pvp=true
allow-flight=false
white-list=false
enable-command-block=true
spawn-npcs=true
spawn-animals=true
spawn-monsters=true
spawn-protection=16
view-distance=10
simulation-distance=10
