// ============================================================
// 文明纪元 - 万物皆可交易：动态价格生成器（服务器端）
// 定价逻辑：基础价值 × 稀有度系数 × 材质系数 × 特殊加成
// ============================================================

// ============================================================
// 稀有度系数
// ============================================================

const RARITY_MULTIPLIER = {
  'common': 1.0,
  'uncommon': 2.5,
  'rare': 6.0,
  'epic': 15.0
}

// ============================================================
// 物品类型基础价值
// ============================================================

const CATEGORY_BASE_VALUE = {
  'netherite_item': 500,
  'diamond_item': 150,
  'gold_item': 60,
  'iron_item': 25,
  'stone_item': 8,
  'wooden_item': 3,
  'leather_item': 10,
  'chainmail_item': 20,
  'sword': 30,
  'pickaxe': 35,
  'axe': 25,
  'shovel': 15,
  'hoe': 20,
  'bow': 40,
  'crossbow': 50,
  'trident': 200,
  'helmet': 35,
  'chestplate': 50,
  'leggings': 45,
  'boots': 30,
  'shield': 40,
  'elytra': 800,
  'food': 5,
  'seed': 1,
  'sapling': 2,
  'flower': 1,
  'ore': 20,
  'ingot': 25,
  'gem': 100,
  'dust': 2,
  'nugget': 2,
  'block': 5,
  'stone': 0.5,
  'dirt': 0.1,
  'wood': 2,
  'planks': 1,
  'redstone': 8,
  'potion': 50,
  'enchanted_book': 80,
  'spawn_egg': 200,
  'music_disc': 150,
  'banner': 15,
  'wool': 3,
  'dye': 2,
  'glass': 3,
  'brick': 4,
  'clay': 2,
  'sand': 0.2,
  'gravel': 0.3,
  'cobblestone': 0.5,
  'coal': 3,
  'charcoal': 2,
  'stick': 0.5,
  'string': 1,
  'leather': 8,
  'feather': 2,
  'bone': 1,
  'arrow': 1,
  'torch': 0.3,
  'crafting_table': 3,
  'furnace': 8,
  'chest': 5,
  'barrel': 6,
  'hopper': 30,
  'piston': 20,
  'observer': 15,
  'dispenser': 12,
  'dropper': 10,
  'rail': 3,
  'powered_rail': 8,
  'detector_rail': 6,
  'activator_rail': 5,
  'minecart': 25,
  'tnt': 40,
  'book': 10,
  'paper': 1,
  'ink_sac': 2,
  'ender_pearl': 80,
  'ender_eye': 150,
  'blaze_rod': 30,
  'blaze_powder': 15,
  'ghast_tear': 60,
  'magma_cream': 20,
  'slime_ball': 8,
  'gunpowder': 5,
  'rotten_flesh': 0.2,
  'bone_meal': 2,
  'experience_bottle': 100,
  'golden_apple': 300,
  'enchanted_golden_apple': 5000,
  'nether_star': 2000,
  'dragon_egg': 10000,
  'wither_rose': 100,
  'heart_of_the_sea': 500,
  'totem_of_undying': 400,
  'shulker_shell': 120,
  'chorus_fruit': 10,
  'phantom_membrane': 80,
  'trident_item': 250,
  'nautilus_shell': 60,
  'rabbit_foot': 20,
  'glow_berries': 3,
  'amethyst': 15,
  'copper': 8,
  'raw_iron': 12,
  'raw_copper': 4,
  'raw_gold': 30,
  'deepslate': 0.3,
  'tuff': 0.2,
  'calcite': 0.2,
  'dripstone': 0.1,
  'moss_block': 1,
  'moss_carpet': 0.5,
  'small_dripleaf': 1,
  'big_dripleaf': 2,
  'spore_blossom': 5,
  'glow_lichen': 1,
  'sculk': 10,
  'sculk_sensor': 25,
  'sculk_shrieker': 50,
  'sculk_catalyst': 40,
  'echo_shard': 150,
  'recovery_compass': 200,
  'allay_spawn_egg': 500,
  'frog_spawn': 5,
  'tadpole_bucket': 20,
  'frog': 50,
  'mud': 0.1,
  'packed_mud': 0.2,
  'mud_brick': 1,
  'mangrove': 2
}

// ============================================================
// 特殊物品价格表（精确覆盖）
// ============================================================

const SPECIAL_PRICES = {
  'minecraft:dirt': 0.1,
  'minecraft:cobblestone': 0.5,
  'minecraft:stone': 0.5,
  'minecraft:gravel': 0.3,
  'minecraft:sand': 0.2,
  'minecraft:clay_ball': 2,
  'minecraft:clay': 2,
  'minecraft:oak_planks': 1,
  'minecraft:spruce_planks': 1,
  'minecraft:birch_planks': 1,
  'minecraft:jungle_planks': 1,
  'minecraft:acacia_planks': 1,
  'minecraft:dark_oak_planks': 1,
  'minecraft:mangrove_planks': 1,
  'minecraft:oak_log': 2,
  'minecraft:spruce_log': 2,
  'minecraft:birch_log': 2,
  'minecraft:stick': 0.5,
  'minecraft:coal': 3,
  'minecraft:charcoal': 2,
  'minecraft:torch': 0.3,
  'minecraft:crafting_table': 3,
  'minecraft:furnace': 8,
  'minecraft:chest': 5,
  'minecraft:barrel': 6,
  'minecraft:iron_ingot': 25,
  'minecraft:gold_ingot': 60,
  'minecraft:copper_ingot': 8,
  'minecraft:netherite_ingot': 1000,
  'minecraft:diamond': 200,
  'minecraft:emerald': 150,
  'minecraft:lapis_lazuli': 12,
  'minecraft:redstone': 10,
  'minecraft:quartz': 8,
  'minecraft:glowstone_dust': 3,
  'minecraft:iron_ore': 15,
  'minecraft:gold_ore': 40,
  'minecraft:diamond_ore': 120,
  'minecraft:coal_ore': 2,
  'minecraft:copper_ore': 5,
  'minecraft:lapis_ore': 8,
  'minecraft:redstone_ore': 6,
  'minecraft:deepslate_iron_ore': 18,
  'minecraft:deepslate_gold_ore': 45,
  'minecraft:deepslate_diamond_ore': 130,
  'minecraft:deepslate_coal_ore': 3,
  'minecraft:deepslate_copper_ore': 6,
  'minecraft:deepslate_lapis_ore': 10,
  'minecraft:deepslate_redstone_ore': 8,
  'minecraft:ancient_debris': 600,
  'minecraft:netherite_scrap': 250,
  'minecraft:iron_sword': 30,
  'minecraft:iron_pickaxe': 35,
  'minecraft:iron_axe': 25,
  'minecraft:iron_shovel': 15,
  'minecraft:iron_hoe': 20,
  'minecraft:diamond_sword': 250,
  'minecraft:diamond_pickaxe': 300,
  'minecraft:diamond_axe': 200,
  'minecraft:diamond_shovel': 120,
  'minecraft:diamond_hoe': 150,
  'minecraft:netherite_sword': 1500,
  'minecraft:netherite_pickaxe': 1800,
  'minecraft:netherite_axe': 1200,
  'minecraft:netherite_shovel': 800,
  'minecraft:netherite_hoe': 1000,
  'minecraft:iron_helmet': 35,
  'minecraft:iron_chestplate': 50,
  'minecraft:iron_leggings': 45,
  'minecraft:iron_boots': 30,
  'minecraft:diamond_helmet': 200,
  'minecraft:diamond_chestplate': 300,
  'minecraft:diamond_leggings': 250,
  'minecraft:diamond_boots': 180,
  'minecraft:netherite_helmet': 1200,
  'minecraft:netherite_chestplate': 1800,
  'minecraft:netherite_leggings': 1500,
  'minecraft:netherite_boots': 1000,
  'minecraft:shield': 40,
  'minecraft:bow': 40,
  'minecraft:crossbow': 50,
  'minecraft:arrow': 1,
  'minecraft:trident': 250,
  'minecraft:elytra': 800,
  'minecraft:ender_pearl': 80,
  'minecraft:ender_eye': 150,
  'minecraft:blaze_rod': 30,
  'minecraft:blaze_powder': 15,
  'minecraft:ghast_tear': 60,
  'minecraft:magma_cream': 20,
  'minecraft:slime_ball': 8,
  'minecraft:gunpowder': 5,
  'minecraft:rotten_flesh': 0.2,
  'minecraft:bone': 1,
  'minecraft:bone_meal': 2,
  'minecraft:feather': 2,
  'minecraft:leather': 8,
  'minecraft:string': 1,
  'minecraft:wheat': 2,
  'minecraft:wheat_seeds': 0.5,
  'minecraft:bread': 5,
  'minecraft:carrot': 3,
  'minecraft:potato': 3,
  'minecraft:beetroot': 3,
  'minecraft:beetroot_seeds': 0.3,
  'minecraft:apple': 4,
  'minecraft:golden_apple': 300,
  'minecraft:enchanted_golden_apple': 5000,
  'minecraft:steak': 6,
  'minecraft:cooked_beef': 6,
  'minecraft:raw_beef': 3,
  'minecraft:porkchop': 5,
  'minecraft:cooked_porkchop': 5,
  'minecraft:chicken': 3,
  'minecraft:cooked_chicken': 4,
  'minecraft:mutton': 3,
  'minecraft:cooked_mutton': 4,
  'minecraft:fish': 3,
  'minecraft:cod': 3,
  'minecraft:salmon': 4,
  'minecraft:cooked_cod': 4,
  'minecraft:cooked_salmon': 5,
  'minecraft:milk_bucket': 10,
  'minecraft:water_bucket': 3,
  'minecraft:lava_bucket': 20,
  'minecraft:bucket': 10,
  'minecraft:experience_bottle': 100,
  'minecraft:nether_star': 2000,
  'minecraft:dragon_egg': 10000,
  'minecraft:wither_rose': 100,
  'minecraft:heart_of_the_sea': 500,
  'minecraft:totem_of_undying': 400,
  'minecraft:shulker_shell': 120,
  'minecraft:shulker_box': 250,
  'minecraft:hopper': 30,
  'minecraft:piston': 20,
  'minecraft:sticky_piston': 25,
  'minecraft:observer': 15,
  'minecraft:dispenser': 12,
  'minecraft:dropper': 10,
  'minecraft:redstone_repeater': 8,
  'minecraft:redstone_comparator': 12,
  'minecraft:daylight_detector': 10,
  'minecraft:note_block': 8,
  'minecraft:jukebox': 50,
  'minecraft:enchanting_table': 80,
  'minecraft:anvil': 40,
  'minecraft:grindstone': 15,
  'minecraft:smithing_table': 20,
  'minecraft:fletching_table': 8,
  'minecraft:cartography_table': 8,
  'minecraft:book': 10,
  'minecraft:bookshelf': 15,
  'minecraft:paper': 1,
  'minecraft:map': 8,
  'minecraft:compass': 12,
  'minecraft:clock': 12,
  'minecraft:tnt': 40,
  'minecraft:tnt_minecart': 50,
  'minecraft:minecart': 25,
  'minecraft:furnace_minecart': 30,
  'minecraft:chest_minecart': 30,
  'minecraft:hopper_minecart': 50,
  'minecraft:rail': 3,
  'minecraft:powered_rail': 8,
  'minecraft:detector_rail': 6,
  'minecraft:activator_rail': 5,
  'minecraft:oak_sapling': 2,
  'minecraft:spruce_sapling': 2,
  'minecraft:birch_sapling': 2,
  'minecraft:jungle_sapling': 2,
  'minecraft:acacia_sapling': 2,
  'minecraft:dark_oak_sapling': 2,
  'minecraft:oak_leaves': 0.2,
  'minecraft:spruce_leaves': 0.2,
  'minecraft:poppy': 1,
  'minecraft:dandelion': 1,
  'minecraft:rose_bush': 2,
  'minecraft:lilac': 2,
  'minecraft:peony': 2,
  'minecraft:tulip': 1,
  'minecraft:wool': 3,
  'minecraft:carpet': 1,
  'minecraft:painting': 20,
  'minecraft:item_frame': 10,
  'minecraft:glow_item_frame': 30,
  'minecraft:armor_stand': 15,
  'minecraft:banner': 15,
  'minecraft:bed': 20,
  'minecraft:oak_door': 5,
  'minecraft:iron_door': 15,
  'minecraft:oak_fence': 3,
  'minecraft:oak_fence_gate': 4,
  'minecraft:iron_bars': 2,
  'minecraft:glass': 3,
  'minecraft:glass_pane': 1,
  'minecraft:brick': 4,
  'minecraft:bricks': 5,
  'minecraft:stone_bricks': 5,
  'minecraft:cobblestone_stairs': 2,
  'minecraft:stone_stairs': 3,
  'minecraft:oak_stairs': 3,
  'minecraft:brick_stairs': 6,
  'minecraft:stone_brick_stairs': 6,
  'minecraft:slime_block': 80,
  'minecraft:honey_block': 60,
  'minecraft:honeycomb': 8,
  'minecraft:honey_bottle': 15,
  'minecraft:beehive': 40,
  'minecraft:bee_nest': 60,
  'minecraft:raw_copper': 4,
  'minecraft:raw_iron': 12,
  'minecraft:raw_gold': 30,
  'minecraft:copper_block': 72,
  'minecraft:raw_copper_block': 36,
  'minecraft:raw_iron_block': 108,
  'minecraft:raw_gold_block': 270,
  'minecraft:lightning_rod': 30,
  'minecraft:spyglass': 80,
  'minecraft:bundle': 50,
  'minecraft:amethyst_shard': 15,
  'minecraft:amethyst_block': 60,
  'minecraft:tinted_glass': 10,
  'minecraft:pointed_dripstone': 0.5,
  'minecraft:dripstone_block': 0.5,
  'minecraft:moss_block': 1,
  'minecraft:moss_carpet': 0.5,
  'minecraft:small_dripleaf': 1,
  'minecraft:big_dripleaf': 2,
  'minecraft:spore_blossom': 5,
  'minecraft:glow_lichen': 1,
  'minecraft:glow_squid_spawn_egg': 200,
  'minecraft:glow_ink_sac': 8,
  'minecraft:glow_item_frame': 30,
  'minecraft:sculk': 10,
  'minecraft:sculk_sensor': 25,
  'minecraft:sculk_shrieker': 50,
  'minecraft:sculk_catalyst': 40,
  'minecraft:sculk_vein': 5,
  'minecraft:echo_shard': 150,
  'minecraft:recovery_compass': 200,
  'minecraft:warden_spawn_egg': 1000,
  'minecraft:disc_fragment_5': 200,
  'minecraft:allay_spawn_egg': 500,
  'minecraft:frog_spawn': 5,
  'minecraft:tadpole_bucket': 20,
  'minecraft:frog_spawn_egg': 300,
  'minecraft:mud': 0.1,
  'minecraft:packed_mud': 0.2,
  'minecraft:mud_brick': 1,
  'minecraft:mud_bricks': 4,
  'minecraft:mangrove_log': 2,
  'minecraft:mangrove_planks': 1,
  'minecraft:mangrove_roots': 1,
  'minecraft:mangrove_propagule': 2,
  'minecraft:mangrove_frog_spawn_egg': 300,
  'minecraft:tropical_fish_bucket': 25,
  'minecraft:pufferfish_bucket': 20,
  'minecraft:axolotl_bucket': 80,
  'minecraft:axolotl_spawn_egg': 400,
  'minecraft:goat_spawn_egg': 250,
  'minecraft:goat_horn': 150,
  'minecraft:music_disc_13': 150,
  'minecraft:music_disc_cat': 150,
  'minecraft:music_disc_blocks': 150,
  'minecraft:music_disc_chirp': 150,
  'minecraft:music_disc_far': 150,
  'minecraft:music_disc_mall': 150,
  'minecraft:music_disc_mellohi': 150,
  'minecraft:music_disc_stal': 150,
  'minecraft:music_disc_strad': 150,
  'minecraft:music_disc_ward': 150,
  'minecraft:music_disc_11': 200,
  'minecraft:music_disc_wait': 180,
  'minecraft:music_disc_otherside': 150,
  'minecraft:music_disc_pigstep': 200,
  'minecraft:music_disc_5': 250,
  'minecraft:music_disc_relic': 300,
  'minecraft:saddle': 60,
  'minecraft:horse_armor_iron': 80,
  'minecraft:horse_armor_gold': 100,
  'minecraft:horse_armor_diamond': 250,
  'minecraft:name_tag': 30,
  'minecraft:lead': 15,
  'minecraft:bell': 25,
  'minecraft:campfire': 10,
  'minecraft:soul_campfire': 15,
  'minecraft:lantern': 10,
  'minecraft:soul_lantern': 15,
  'minecraft:jack_o_lantern': 5,
  'minecraft:pumpkin': 2,
  'minecraft:melon': 3,
  'minecraft:melon_slice': 1,
  'minecraft:glistering_melon_slice': 10,
  'minecraft:fermented_spider_eye': 8,
  'minecraft:spider_eye': 3,
  'minecraft:glass_bottle': 2,
  'minecraft:potion': 50,
  'minecraft:splash_potion': 60,
  'minecraft:lingering_potion': 80,
  'minecraft:dragon_breath': 100,
  'minecraft:enchanted_book': 80,
  'minecraft:quill': 5,
  'minecraft:ink_sac': 2,
  'minecraft:writeable_book': 8,
  'minecraft:writable_book': 8,
  'minecraft:chain': 5,
  'minecraft:sweet_berries': 2,
  'minecraft:glow_berries': 3,
  'minecraft:kelp': 0.5,
  'minecraft:dried_kelp': 1,
  'minecraft:bamboo': 1,
  'minecraft:lily_pad': 2,
  'minecraft:vine': 0.5,
  'minecraft:fern': 0.3,
  'minecraft:large_fern': 0.5,
  'minecraft:dead_bush': 0.1,
  'minecraft:cactus': 1,
  'minecraft:sugar_cane': 1,
  'minecraft:cocoa_beans': 3,
  'minecraft:brown_mushroom': 1,
  'minecraft:red_mushroom': 1,
  'minecraft:mushroom_stew': 5,
  'minecraft:rabbit_stew': 8,
  'minecraft:beetroot_soup': 5,
  'minecraft:suspicious_stew': 20,
  'minecraft:cookie': 3,
  'minecraft:cake': 20,
  'minecraft:pumpkin_pie': 8,
  'minecraft:rabbit_foot': 20,
  'minecraft:rabbit_hide': 3,
  'minecraft:iron_horse_armor': 80,
  'minecraft:golden_horse_armor': 100,
  'minecraft:diamond_horse_armor': 250,
  'minecraft:trident': 250,
  'minecraft:nautilus_shell': 60,
  'minecraft:heart_of_the_sea': 500,
  'minecraft:conduit': 600,
  'minecraft:turtle_helmet': 100,
  'minecraft:scute': 15,
  'minecraft:phantom_membrane': 80,
  'minecraft:dragon_breath': 100,
  'minecraft:end_crystal': 200,
  'minecraft:chorus_fruit': 10,
  'minecraft:popped_chorus_fruit': 15,
  'minecraft:ender_dragon_spawn_egg': 5000,
  'minecraft:wither_spawn_egg': 3000,
  'minecraft:warden_spawn_egg': 1000
}

// ============================================================
// 动态价格生成函数
// ============================================================

function generateDynamicPrices() {
  let items = {}

  for (let [itemId, price] of Object.entries(SPECIAL_PRICES)) {
    items[itemId] = {
      base_price: price,
      base_supply_per_day: Math.max(1, 100 / (price + 1)),
      base_demand_per_day: Math.max(1, 80 / (price + 1)),
      price_elasticity: price > 100 ? -1.2 : price > 20 ? -0.8 : -0.4,
      category: getCategoryFromId(itemId),
      era: getEraFromPrice(price),
      faction: getFactionFromCategory(getCategoryFromId(itemId))
    }
  }

  return items
}

function getCategoryFromId(itemId) {
  let id = itemId.replace('minecraft:', '')
  if (id.includes('sword')) return 'weapon'
  if (id.includes('pickaxe')) return 'tool'
  if (id.includes('axe')) return 'tool'
  if (id.includes('shovel')) return 'tool'
  if (id.includes('hoe')) return 'tool'
  if (id.includes('helmet')) return 'armor'
  if (id.includes('chestplate')) return 'armor'
  if (id.includes('leggings')) return 'armor'
  if (id.includes('boots')) return 'armor'
  if (id.includes('ore')) return 'mineral'
  if (id.includes('ingot')) return 'mineral'
  if (id.includes('gem')) return 'gem'
  if (id.includes('diamond')) return 'gem'
  if (id.includes('emerald')) return 'gem'
  if (id.includes('food') || id.includes('cooked') || (id.includes('raw_') && !id.includes('iron') && !id.includes('gold') && !id.includes('copper'))) return 'food'
  if (id.includes('bread') || id.includes('apple') || id.includes('steak') || id.includes('chicken') || id.includes('mutton') || id.includes('porkchop') || id.includes('beef')) return 'food'
  if (id.includes('seed') || id.includes('sapling')) return 'nature'
  if (id.includes('potion') || id.includes('enchanted')) return 'magic'
  if (id.includes('music_disc')) return 'collectible'
  if (id.includes('spawn_egg')) return 'rare'
  if (id.includes('elytra') || id.includes('dragon_egg') || id.includes('nether_star') || id.includes('totem')) return 'legendary'
  return 'misc'
}

function getEraFromPrice(price) {
  if (price < 1) return 0
  if (price < 5) return 1
  if (price < 15) return 2
  if (price < 50) return 3
  if (price < 150) return 4
  if (price < 400) return 5
  if (price < 1000) return 6
  return 7
}

function getFactionFromCategory(category) {
  switch (category) {
    case 'food':
    case 'nature':
      return 'farmers_union'
    case 'mineral':
    case 'tool':
      return 'miners_guild'
    case 'weapon':
    case 'armor':
      return 'guard_corps'
    case 'magic':
    case 'gem':
      return 'academy'
    case 'rare':
    case 'legendary':
    case 'collectible':
      return 'underground_market'
    default:
      return 'industrial_consortium'
  }
}

// ============================================================
// 生成完整的市场配置
// ============================================================

const DYNAMIC_MARKET_ITEMS = generateDynamicPrices()

const MARKET_CONFIG = {
  currency: {
    base_unit: '金币',
    copper_to_silver: 100,
    silver_to_gold: 100
  },
  market_settings: {
    update_interval_ticks: 24000,
    daily_price_change_limit: 0.15,
    decay_rate_per_day: 0.03,
    target_inventory_days: 7,
    price_adjustment_speed: 0.3,
    min_price_ratio: 0.3,
    max_price_ratio: 3.0,
    supply_shock_min: 0.85,
    supply_shock_max: 1.15
  },
  items: DYNAMIC_MARKET_ITEMS
}

global.MARKET_CONFIG = MARKET_CONFIG
global.DYNAMIC_MARKET_ITEMS = DYNAMIC_MARKET_ITEMS
global.generateDynamicPrices = generateDynamicPrices
